name: Coverage

# Skip this step for now since the upload action seems to be broken:
# https://github.com/codecov/codecov-action/issues/37
on:
  push:
    branches-ignore:
      - '**'

jobs:
  test:

    runs-on: ubuntu-latest
    
    container:
      image: xd009642/tarpaulin
      options: --security-opt seccomp=unconfined

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run tests
        run: cargo tarpaulin -v --out Xml
      - name: Upload coverage
        uses: codecov/codecov-action@v1
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          fail_ci_if_error: true
